### ISSUE TITLE
I don't speak German

### ISSUE THREAD

**Issue by C-Fu** [dtpnk/docker-portfolio#6]
How do I change to English? No offense but I thought having the README in English would also mean the container app will be in English as well

**Comment by B1ue-W01f** [comment]
@C-Fu I dont suppose youve figured it out have you? I know enough german to get to the language menu but I appear to just get an error message when changing - which Im not good enough to understand.

**Comment by ghost** [comment]
Not sure if you still need this, but restarting the docker container fixed this for me.

**Comment by devben-io** [comment]
Hi @C-Fu, @B1ue-W01f and @VoIP,
sorry for the late reply.

I fixed it in this [PR](https://github.com/dtpnk/docker-portfolio/pull/7)
The language can now be configured in the docker build step.
The default language is now english.

Cheers
